; Metamod plugins.ini
; Format: <platform> <path relative to game directory>
; AMX Mod X core (aarch64 build, stored as libamxmodx.so in the app native dir)
linux addons/amxmodx/libamxmodx.so
; YaPB Counter-Strike bot
linux addons/yapb/bin/libyapb.so
